/*
 * Buoy Estimation Filter - buoy_estimation_filter.h
 * Intelligent Filter trying to estimate a real buoy in 
 * a given feature vector
 * 
 * created by: 
 *     TODO: 
 */

#ifndef VISUAL_DETECTORS__BUOY_PARADISE_FILTER_H_
#define VISUAL_DETECTORS__BUOY_PARADISE_FILTER_H_

#include <stddef.h>
#include <opencv/cv.h>
#include <list>
#include "buoy_interface.h"
#include <avalon_base/feature.h>
#include <stdio.h>
#include <math.h>
#include <vector>
#include <algorithm>
#include "base/time.h"

namespace avalon {

//typedef std::vector<feature::Buoy> BuoyFeatureVector;

/**
 * A Buoy estimation filter who is searching the best possible
 * match of a buoy in a given set of feature vectors over the time.
 */
class BuoyParadiseFilter : public BuoyFilter 
{
 
 public:
    /** 
     * generates a standard buoy estimation filter with default configuration
     */
    BuoyParadiseFilter();

    /** 
     * standard destructor for releasing all allocated resources
     */
    ~BuoyParadiseFilter();

    feature::Buoy radius_filter(BuoyFeatureVector& buoys);
    
    
    /**
     * returns the feature of the best possible recognized buoy for a given set of data
     * @return buoy feature of the best possible match
     */
    BuoyFeatureVector process();

    /**
     * add feature vector to this filter in order to estimate the best possible match
     * @param vector a feature vector that is generated by a buoy detector
     */
    void feed(const BuoyFeatureVector& input_vector);

    void doTimestep();
    
    

    void setBufferSize(unsigned int i);
    void setMinSize(unsigned int i);
    void setStartval(unsigned int i);
    void setMindist(unsigned int i);
    void setMaxage(unsigned int i);

 private:

    void setValidations(BuoyFeatureVector& vector);
    void mergeVectors(BuoyFeatureVector& vector);
    

    std::vector<BuoyFeatureVector> buoys_buffer;

    // maximum number of buoys to be part of one BuoyFeatureVector
    unsigned int buoys_buffer_size;

    // minimum number of buoys in a BuoyFeatureVector to make it valid
    int buoys_buffer_size_min;

    // validation von der ausgehend die validation der buoys berechnet wird
    double startvalidation;

    // minimum distance between buoys to be part of the same BuoyFeatureVector
    double mindist;
    
    // maximales alter einer Buoy in einem BuoyFeatureVector
    int64_t maxage;

};

} // namespace avalon

#endif // VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_

