/*
 * Buoy Estimation Filter - buoy_estimation_filter.h
 * Intelligent Filter trying to estimate a real buoy in 
 * a given feature vector
 * 
 * created by: 
 *     TODO: 
 */

#ifndef VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_
#define VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_

#include <stddef.h>
#include <opencv/cv.h>
#include <list>
#include "buoy_interface.h"
#include <stdio.h>

namespace avalon {

/**
 * A Buoy estimation filter who is searching the best possible
 * match of a buoy in a given set of feature vectors over the time.
 */
class BuoyEstimationFilter : public BuoyFilter {
 
 public:
    /** 
     * generates a standard buoy estimation filter with default configuration
     */
    BuoyEstimationFilter();

    /** 
     * standard destructor for releasing all allocated resources
     */
    ~BuoyEstimationFilter();

    /**
     * has the filter already found a buoy in a given data source (feature vectors)
     * @return true if a real buoy is detected
     */
    bool isBuoyFound() const;

    /**
     * returns the feature of the best possible recognized buoy for a given set of data
     * @return buoy feature of the best possible match
     */
    BuoyFeatureVector process();

    /**
     * add feature vector to this filter in order to estimate the best possible match
     * @param vector a feature vector that is generated by a buoy detector
     */
    void feed(const BuoyFeatureVector& vector);


    /**
     * sets the size of the feature buffer processed by this filter
     * @param size current size of the buffer
     */
     void configureFeatureBufferSize(int size) { 
         feature_buffer_size = size;
     }

 private:
    bool checkLocation(CvPoint location, int radius) const;

    double getAverageRadius() const;

 private:
    std::list<BuoyFeatureVector> features;
    std::list<BuoyFeatureVector> features_history;

    // maximum number of feature vectors analysed by this filter
    size_t feature_buffer_size;

    // last location found of a buoy
    CvPoint last_location;
    // e.g. more logic
};

} // namespace avalon

#endif // VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_

