/*
 * Buoy Estimation Filter - buoy_estimation_filter.h
 * Intelligent Filter trying to estimate a real buoy in 
 * a given feature vector
 * 
 * created by: 
 *     TODO: 
 */


#ifndef VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_
#define VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_

#include "buoy_detector.h"

namespace avalon {

/**
 * A Buoy estimation filter who is searching the best possible
 * match of a buoy in a given set of feature vectors over the time.
 */
class BuoyEstimationFilter {
 
 public:
    /** 
     * generates a standard buoy estimation filter with default configuration
     */
    BuoyEstimationFilter();

    /** 
     * standard destructor for releasing all allocated resources
     */
    ~BuoyEstimationFilter();

    /**
     * has the filter already found a buoy in a given data source (feature vectors)
     * @return true if a real buoy is detected
     */
    bool hasBuoyFound() const;

    /**
     * returns the feature of the best possible recognized buoy for a given set of data
     * @return buoy feature of the best possible match
     */
    feature::Buoy getBestFeature() const;

    /**
     * add feature vector to this filter in order to estimate the best possible match
     * @param vector a feature vector that is generated by a buoy detector
     */
    void feed(const BuoyFeatureVector& vector);

 private:
    std::vector<BuoyFeatureVector> features;

    // e.g. more logic
};

} // namespace avalon

#endif // VISUAL_DETECTORS__BUOY_ESTIMATION_FILTER_H_

